### ISSUE TITLE
it seems the inference speed is slow!

### ISSUE THREAD

**Issue by visonpon** [jialee93/Improved-Body-Parts#10]
Hi, @jialee93 
Thanks for your great work. When I use `demo_images.py` to test on my own image , each image consumes about 40 seconds(TitianV)!. But as you said in the readme, the speed has achived real time. I don't know why and hope you can give some advice~

**Comment by jialee93** [comment]
Hi, first please check your environment configurations again. The speed is tested using pure python and in single process, please refer to the testing details in the readme. The postprocessing procedure can be improved and it has not been well done for release. Note that the keypoint assignment is based on greedy connection, which can be parallelly done in several independent processes.

**Comment by hellojialee** [comment]
For now, you can refer to this issue #20:
https://github.com/hellojialee/Improved-Body-Parts/issues/20#issuecomment-633406270
I'm doing a further work and it really needs more time.
