### ISSUE TITLE
how to inferencce on video？

### ISSUE THREAD

**Issue by huaqi19** [jialee93/Improved-Body-Parts#14]

**Comment by huaqi19** [comment]
hello，I want to  inference my videos， what should i do？

**Comment by huaqi19** [comment]
hello，I want to  inference my videos， what should i do？

**Comment by huaqi19** [comment]
Oh， I do。我做好了，我发现有的帧腿就没了

**Comment by huaqi19** [comment]
![image](https://user-images.githubusercontent.com/60562661/76403355-c304da80-63bf-11ea-8b68-5cd32e427cd7.png)

**Comment by jialee93** [comment]
The image sample you tested above seems easy, what scale configurations did you use? 
For single scale inference, 768 length is better than 512:
https://github.com/jialee93/Improved-Body-Parts/blob/316e71fa93e1dc444b1cfd4fc312c21c13bfe93f/utils/config#L36

And lower threshold thre1=thre2=0.08 is better for more keypoint detection if the background is not very complexed:
https://github.com/jialee93/Improved-Body-Parts/blob/316e71fa93e1dc444b1cfd4fc312c21c13bfe93f/utils/config#L16
