### ISSUE TITLE
Joints heatmaps

### ISSUE THREAD

**Issue by bhack** [jialee93/Improved-Body-Parts#18]
Hi I want to ask you what we have in the multi-person joints heatmap generated with the heatmapper.
Is It just a gaussian around each joint location so that the same semantic joint (i.e. left shoulder) is on the same heatmap channel for all the human targets in the scene but at different x,y location?

So could you vectorize the joint heatmapper emitter i.e. with [render gaussian](https://kornia.readthedocs.io/en/latest/geometry.html#kornia.geometry.render_gaussian_2d)? Cause I see you have many loop there with numpy code and so I am guessing if It could be vectorized with some Pytorch ops.

**Comment by jialee93** [comment]
Yes, you are right. 

The code has already used python slice and np.outer trick, thus the speed is fast enough for preparing training data. I will consider your advice if I have time. Thank you for your sharing!

**Comment by bhack** [comment]
@jialee93 Thank for your reply. I have another question have you experimented with Spatial argmax for the joints?
I am asking this cause I know that this is a reference impl of you paper but a found an interesting trick recently in https://arxiv.org/abs/2003.07543 that could be interesting with joints.

**Comment by jialee93** [comment]
No, I have not. Thank you for your sharing, looks like they use different encoding method try to get more accurate response and introduce scale awareness. The idea of Gaussian response refinement is frequently visited. The encoding, heatmap upsampling and direct argmax can restore the joints location within 1 pixel offset. However, the main bottleneck in our project is object scale variance.

**Comment by bhack** [comment]
>  However, the main bottleneck in our project is object scale variance.
Yes exactly.. it is why It was interesting if the Scale adaptive soft-argmax operator trick could cover you variance also cause the number of the (discrete) scale channels could be adapted.

**Comment by jialee93** [comment]
Thank you for your advice.  And please let me know if you discover more :)

**Comment by bhack** [comment]
Yes in their case It Is still not clear to me how they handle the multi-modal peak inside the same heatmap channel with a soft-argmax.
