### ISSUE TITLE
Test without multi scale and flip

### ISSUE THREAD

**Issue by BobDL** [jialee93/Improved-Body-Parts#5]
Hi,
  Thanks for your job and the project. I have demo the pretrained model on some pics. With the default setting( with FLIP, multi scale) the pose result is OK, similar to the openpose BODY25 model. But, if without the flip, and multi scale, the result is not so good even on very simple image.
Could you help check if any issue there?

origin image
![2](https://user-images.githubusercontent.com/51008026/70143772-6c5c7600-16d7-11ea-8e21-5ddfb6b69581.jpg)

with flip
![result_withflip](https://user-images.githubusercontent.com/51008026/70143715-4df67a80-16d7-11ea-95cb-83e9cd8e24f8.jpg)

without flip
![result_woflip](https://user-images.githubusercontent.com/51008026/70143716-4df67a80-16d7-11ea-8fbb-20bf4a2f8eee.jpg)

**Comment by jialee93** [comment]
Predict on one scale (512 input) without flip:
![result](https://user-images.githubusercontent.com/21237799/70150480-07a81800-16e5-11ea-98a7-a827e8d6bd39.jpg)
 I guess you may miss some fixed body part channels (looking at your result, the connection between neck and right hip is missing).

**Comment by BobDL** [comment]
> Predict on one scale (512 input) without flip:
> ![result](https://user-images.githubusercontent.com/21237799/70150480-07a81800-16e5-11ea-98a7-a827e8d6bd39.jpg)
> I guess you may miss some fixed body part channels (looking at your result, the connection between neck and right hip is missing).

OK, thanks. You are right. It's good after fix a bug.
