### ISSUE TITLE
With the evaluate.py

### ISSUE THREAD

**Issue by A7777-gp** [jialee93/Improved-Body-Parts#54]
![1633764593(1)](https://user-images.githubusercontent.com/71368612/136648853-d8a8253f-f61c-4197-8429-15b6cd91ee19.png)

**Comment by A7777-gp** [comment]
I did not find the path of the input_image_path

**Comment by hellojialee** [comment]
Is this what you are looking for?

https://github.com/hellojialee/Improved-Body-Parts/blob/0fa17dff1ea829c2951c18185d5f1ce7fe0072fc/evaluate.py#L502
