### ISSUE TITLE
Pretrained model provided on Google Drive?

### ISSUE THREAD

**Issue by murdockhou** [jialee93/Improved-Body-Parts#6]
Hi, thanks for your work. Can you provide pretrained model on google drive? It's too slow to down model on BaiduNetDisk. Thanks a lot.

**Comment by jialee93** [comment]
Hi, it is not convenient for me to upload the pretreated models on google drive. Alternatively, you can only download a single model weight file via this [link](https://drive.google.com/open?id=1gLa2oNxnbFPo0BjnpPaiAmWJwyND8wkA) for evaluation under the default configurations. Please dot not forget rename the file and path accordingly.

**Comment by murdockhou** [comment]
@jialee93 Thanks~
