### ISSUE TITLE
Heatmap Visualization

### ISSUE THREAD

**Issue by A7777-gp** [jialee93/Improved-Body-Parts#67]
Hello, what part of the code is the visualization of the heat map? How can I get it?

**Comment by hellojialee** [comment]
In this repo, I use the stupid method: https://github.com/hellojialee/Improved-Body-Parts/blob/0fa17dff1ea829c2951c18185d5f1ce7fe0072fc/demo_image.py#L64

**Comment by A7777-gp** [comment]
Thanks!!!  But in demo_image.py, the last output is the human body posture, may I ask which line of code in demo_image.py can be modified to output the heat map of key points?

**Comment by hellojialee** [comment]
Here:
https://github.com/hellojialee/Improved-Body-Parts/blob/0fa17dff1ea829c2951c18185d5f1ce7fe0072fc/demo_image.py#L98

You can specify which keypoint heatmap to show by its index.

**Comment by A7777-gp** [comment]
May I ask if the key point heat map can be output by executing this line of code?
https://github.com/hellojialee/Improved-Body-Parts/blob/0fa17dff1ea829c2951c18185d5f1ce7fe0072fc/demo_image.py#L191

**Comment by A7777-gp** [comment]
I'm sorry. I'm a terrible coder😭

**Comment by hellojialee** [comment]
> May I ask if the key point heat map can be output by executing this line of code?
> 
> https://github.com/hellojialee/Improved-Body-Parts/blob/0fa17dff1ea829c2951c18185d5f1ce7fe0072fc/demo_image.py#L191

Yes.  No apologies ：）
