### ISSUE TITLE
Request for licensing information

### ISSUE THREAD

**Issue by Bing-BAI** [jialee93/Improved-Body-Parts#68]
I hope this message finds you well. I came across your project on GitHub and I'm impressed with its capabilities. However, I noticed that there is no information about the licensing of the project.

I would like to inquire about the licensing of this project and whether it can be used for commercial purposes. I am interested in using your project to develop a commercial software, and I need to know the licensing terms before proceeding.

I would greatly appreciate it if you could provide me with more information about the licensing of SimplePose. If there are any specific terms or conditions, please let me know as well.

Thank you very much for your time and assistance. I look forward to hearing from you soon.

Best regards,
Bing BAI

**Comment by hellojialee** [comment]
I grant you the usage permission (including commercial purposes) of this repo only if you will not do bad things :)
