### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by Xj1567589354** [jialee93/Improved-Body-Parts#69]
你好，请问这个库有针对HigherHRNet中valid文件使用的AE分组策略导致的关键点不合理连接的解决方案？

**Comment by hellojialee** [comment]
The keypoint grouping strategy is developed from the original OpenPose. Alternatively, you can find the more fast version of keypoint grouping in my another repo: https://github.com/hellojialee/OffsetGuided/blob/master/decoder/group.py
