### ISSUE TITLE
data/coco_masks_hdf5.py

### ISSUE THREAD

**Issue by weinaike** [jialee93/Improved-Body-Parts#8]
prev_center.append(np.append(person_center, max(img_anns[p]["bbox"][2], img_anns[p]["bbox"][3])))

这里的p是固定值值，是否存在问题？宽高的最大值，是当前main_persons的吗？

**Comment by jialee93** [comment]
The answer to your second question is yes. 
We crop and resize the main person according to the larger value among the person width and hight, and thus, the scale ratio of the main person to the image is a fixed value. But we resize it randomly during training. The main person is centered and the nearby persons are probably included in the cropped patch. This trick can make the data prepare and batch training faster.
We have not tried other crop and resize operations.
