### ISSUE TITLE
How much does multi-scale search contribute?

### ISSUE THREAD

**Issue by WangChen100** [jialee93/Improved-Body-Parts#9]
Hi, from experiment 16 vs 19 in Table 1, we find multi-scale search seems to contribute more than 3% AP.
Did all other models including your baseline in Table 1 have multi-scale search?

**Comment by jialee93** [comment]
About a 3.X% AP increase is observed in my case. But please note that we trained the networks using relatively a small person scale ratio range. This affects the single scale performance, too.

Yes, we have described it clearly in the table and paper context.
